import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'n33r9',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'daisy',
      email: 'admin1@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Yonex',
        logo: '/images/yonexlogo.png',
        description: 'best seller',
        rating: 4.6,
        numReviews: 122,
      },
    },
    {
      name: 'Hieu Tai Tran',
      email: 'Tai@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Minh Thu Ngo',
      email: 'Thu@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Phuong Thao Khong',
      email: 'Thao@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Nike Fashion Shoes',
      category: 'Shoes',
      image: '/images/shoes1.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'NewBalance Sport Shoes',
      category: 'Shoes',
      image: '/images/shoes2.jpg',
      price: 150,
      countInStock: 20,
      brand: 'NB',
      rating: 4.9,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Yankee Shoes',
      category: 'Shoes',
      image: '/images/shoes3.jpg',
      price: 222,
      countInStock: 9,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      name: 'Puma Gold Shoes',
      category: 'Shoes',
      image: '/images/shoes4.jpg',
      price: 190,
      countInStock: 26,
      brand: 'Puma',
      rating: 4.9,
      numReviews: 20,
      description: 'high quality product',
    },
    {
      name: 'Converse All Star vII',
      category: 'Shoes',
      image: '/images/shoes5.jpg',
      price: 110,
      countInStock: 20,
      brand: 'Converse',
      rating: 4.7,
      numReviews: 30,
      description: 'high quality product',
    },
    {
      name: 'Adidas Tennis Skirt',
      category: 'Skirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lining Skirt',
      category: 'Skirts',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Lining',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
};
export default data;
